apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-service
  name: api-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.appPort }}
  selector:
    app: api-service
