apiVersion: v1
kind: Secret
metadata:
  name: api-service
type: Opaque
data:
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  apiKey: {{ .Values.apiKey | b64enc | quote }}
  basicPassword: {{ .Values.basicPassword | b64enc | quote }}
