apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - env:
        - name: SERVE_PORT
          value: {{ .Values.appPort | quote }}
        - name: MONGO_HOST
          value: {{ .Values.mongoHost | quote }}
        - name: MONGO_PORT
          value: {{ .Values.mongoPort | quote }}
        image: {{ .Values.appImage | quote }}
        imagePullPolicy: Always
        name: api-service
        ports:
        - containerPort: {{ .Values.appPort }}
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
