apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
  - name: http
    port: {{ .Values.mongoPort }}
    protocol: TCP
    targetPort: {{ .Values.mongoPort }}
  selector:
    app: mongodb
